# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=200)),
                ('profile', models.ImageField(upload_to='images/profiles')),
            ],
        ),
    ]
